### ISSUE TITLE
adding device setup to example app causes example app project not to build.

### ISSUE THREAD

**Issue by Lcstyle** [particle-iot/spark-setup-android#57]
reproduction steps:
I am using android studio 3.0.1
I cloned a fresh copy of example app repository.  
It builds fine in android studio.
![si-12-44-08-pm_0004](https://user-images.githubusercontent.com/1028272/34418789-de7abc56-ebcd-11e7-85e2-f9a8e022f42f.jpg)

add  compile 'io.particle:devicesetup:0.4.9' to example_app build.gradle

project will no longer compile
![si-12-44-18-pm_0005](https://user-images.githubusercontent.com/1028272/34418785-d5d92af6-ebcd-11e7-99b9-ee79bba19600.jpg)

**Comment by Lcstyle** [comment]
Also, I am adding device setup to my actual android app project, and it also produces similar results.

**Comment by Lcstyle** [comment]
welp.

here's the solution folks:

> solution
> navigate to File/Project Structure...
> make sure your modules has the same Source and Target Compatibility (1.8 in this case)
![2017-12-28_13-06-45](https://user-images.githubusercontent.com/1028272/34419107-00189ed0-ebd0-11e7-8fd1-ed9f6e353c43.jpg)


https://stackoverflow.com/a/46112663

**Comment by Lcstyle** [comment]
I resolved the secondary issue, the main issue is still a problem:
![si-12-44-18-pm_0005](https://user-images.githubusercontent.com/1028272/34418785-d5d92af6-ebcd-11e7-99b9-ee79bba19600.jpg)

**Comment by Lcstyle** [comment]
OK Issue resolved as well.

I removed     
> compile project(':cloudsdk')
and added 
> compile 'io.particle:cloudsdk:0.4.8'
to my example app build.gradle file.

That resolved the first issue.

Any ideas on why this might be happening?

**Comment by CityVibes** [comment]
@Lcstyle First issue happens most likely because  `compile 'io.particle:devicesetup:0.4.9'` already provides `compile 'io.particle:cloudsdk:0.4.8'` thus compiler being unable to solve duplicates from local `compile project(':cloudsdk')` and published library `compile 'io.particle:cloudsdk:0.4.8'
`.

Another issue - with official android studio 3.0 support for Java 8 target 1.8 is now a requirement for this project (retrolambda was removed in favor of full Java 8 support).
